pipeline:
  verify_and_prepare:
    image: java:openjdk-8
    environment:
    - GRADLE_USER_HOME=~/.gradle
    commands:
    - ./gradlew test
    - ./gradlew prepare
    - echo -n "1.0.$DRONE_BUILD_NUMBER,latest" > .tags
    - echo -n "1.0.$DRONE_BUILD_NUMBER" > ./docker/version

  publish_to_docker_hub:
    image: plugins/docker
    repo: eugenezadyra/luxmed-bot
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: ./docker/Dockerfile
    context: ./docker/
    when:
      branch: master
      event: push

  restart_bot:
    image: appleboy/drone-ssh
    host:
      from_secret: digitalocean_host
    username:
      from_secret: digitalocean_user
    key:
      from_secret: digitalocean_key
    script:
    - service luxmed-bot restart
    when:
      branch: master
      event: push